apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: mar11-testrag3-ocp416
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar11-testrag3-ocp416
  name: mar11-testrag3-ocp416
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
