apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mar11-testrag3-ocp416
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar11-testrag3-ocp416
  name: mar11-testrag3-ocp416
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: mar11-testrag3-ocp416
